### PR TITLE
Allow to use any component without warning

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by brightsider** [comment]
@arnaudambro merge it please

**Review by arnaudambro — APPROVED** [review]

**Comment by brightsider** [comment]
@arnaudambro update package version, please.

**Comment by brightsider** [comment]
@arnaudambro ping

**Comment by arnaudambro** [comment]
@brightsider done

**Comment by brightsider** [comment]
@arnaudambro Thanks

**Pull request merged**
