### PR TITLE
[feat] Allowing opposite direction swipe (rtl)

### LINKED ISSUE #2: swipe both ways
hi man thanks for the component, but can u make it swipe both ways

### PR DESCRIPTION
**Pull request by korbav**
Implementing the swipe feature in the opposite direction.

### CODE REVIEW

**Comment by korbav** [comment]
Hi @arnaudambro, would you have some time to review this small PR?

**Comment by arnaudambro** [comment]
sorry @korbav, I was on holidays. Checking it right now
[EDIT] I actually have no time today, I will check it next week...
Sorry !

**Comment by korbav** [comment]
> 
> 
> sorry @korbav, I was on holidays. Checking it right now
> [EDIT] I actually have no time today, I will check it next week...
> Sorry !

Hello, sorry to reach out again, any chance to get this PR reviewed anytime soon?

@arnaudambro Is the project still alive?

**Comment by jakequade** [comment]
Answer seems to be a hard no /shrug.

**Comment by arnaudambro** [comment]
Alright guys, sorry for all this, I've been busy and I forgot....
It's my first open source project and I need your help : 
I just need to merge this PR, that's all I need to do, and it will be updated in npm ?

**Comment by korbav** [comment]
Hello @arnaudambro ,

You will need to :

1 - Check the feature added in this PR is suitable and working as expected
2 - Merge the PR (I already incremented the version of the package.json, you don't have to do it)
3 - Publish the new package to npm using `npm publish`  (FYI and for the future, this final step can be automated with Github actions so that it will be triggered as soon as a merge is detected)

**Pull request merged**
